services:
  - type: web
    name: finance-volatility-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && ./start.sh
    plan: free
    envVars:
      - key: PORT
        value: 8000
